[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_counter = "2hiG8UasvmG2VFUxGWFDbVWwY6MjJ58vdEsVoPUS11pv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rpg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
